### ISSUE TITLE
cljss is not defined

### ISSUE THREAD

**Issue by pbnsilva** [clj-commons/cljss#64]
Hello,

I'm attempting to get started with cljss:
```clojure
(ns dashboard.views
  (:require-macros [cljss.core :as css :refer [defstyles]])
  )

(defstyles my-style []
  {:color "red"}
  )

(defn root
  []
  [:p "this is panel1" {:class (my-style)}]
  )
```

However, I get the error in the console: `cljss is not defined`.

I'm using figwheel and using the dependency `[clj-commons/cljss "1.6.4"]`

What am I missing? Any tips to debug this?

Thank you

**Comment by ychenz** [comment]
@pbnsilva Could you please let me know how did you solve this? I'm having the same issue. Thanks!
